---

# Testing playbook.... use with VM


- hosts: all
  vars:
      centreon_url: "{{ centreon_host }}"
      centreon_api_user: "{{ centreon_user }}"
      centreon_api_pass: "{{ centreon_pass }}"

  handlers:
    - name: "centreon api applycfg"
      centreon_poller:
        url: "{{ centreon_url }}"
        username: "{{ centreon_api_user }}"
        password: "{{ centreon_api_pass }}"
      listen: "centreon api applycfg"
      delegate_to: localhost

  tasks:
    - name: Add {{ ansible_hostname|upper }} ({{ ansible_fqdn }}) to Centreon
      centreon_host:
        url: "{{ centreon_url }}"
        username: "{{ centreon_api_user }}"
        password: "{{ centreon_api_pass }}"
        name: "{{ ansible_hostname }}"
        alias: "{{ ansible_fqdn }}"
        ipaddr: "{{ ansible_fqdn }}"
        hosttemplates:
          - TH_ROOT_GLD_NS 
        hostgroups:
          - HG_APP_DCK
        hostgroups_action: set
        instance: Central
        status: enabled
        state: present
        #opt:
        #  - notes_url: "http://{{ ansible_fqdn }}:4000"
        #  - notes: "DIN secondary server"
        applycfg: True
      delegate_to: localhost
      notify: "centreon api applycfg"
  tags:
    - host


#- hosts: localhost
#  vars:
#    centreon_url: "http://slxr0138.app.eiffage.loc/centreon"
#    centreon_api_user: "test"
#    centreon_api_pass: "F3SPIUI7"
#  tasks:
#    - name: Hostgroup
#      centreon_hostgroup:
#        url: "{{ centreon_url }}"
#        username: "{{ centreon_api_user }}"
#        password: "{{ centreon_api_pass }}"
#        hg:
#          - name: test
#            alias: test
#          - name: test2r
#            alias: test2r
#          - name: test4
#        state: present
#      delegate_to: localhost
#  tags:
#    - hostgroup


#- hosts: localhost
#  vars:
#    centreon_url: "http://slxr0138.app.eiffage.loc/centreon"
#    centreon_api_user: "test"
#    centreon_api_pass: "F3SPIUI7"

#  tasks:
#    - name: Add host to Centreon
#      centreon_host:
#        url: "{{ centreon_url }}"
#        username: "{{ centreon_api_user }}"
#        password: "{{ centreon_api_pass }}"
#        name: "ansible-test"
#        hosttemplates:
#          - OS-Linux-SNMP-custom
#          - App-DB-MySQL
#      delegate_to: localhost
#      notify: "centreon api applycfg"
#  tags:
#    - test


