---
- hosts: windows
  vars:
      centreon_url: "{{ centreon_host }}"
      centreon_api_user: "{{ centreon_user }}"
      centreon_api_pass: "{{ centreon_pass }}"

  tasks:
    - name: Deploy NSCD Client
      win_package:
        path: E:\Ansible\NSCP-0.5.2.35-x64.msi
        state: present
    - name: Checking for a VM target
      debug:
        msg: "{{ ansible_facts[\"nodename\"] }} is a VM"
      when: ansible_virtualization_role == "guest"

