---
- name: restart nrpe_agent
  service:
    name: nrpe
    state: restarted
  become: yes

- name: Commit centreon configuration
  centreon_poller:
    url: "{{ centreon_url }}"
    username: "{{ centreon_api_user }}"
    password: "{{ centreon_api_pass }}"
  listen: "cent_api_applycfg"
  delegate_to: localhost
