---
- name: DB query
  debug:
    msg: "{{ query }}"
    verbosity: "{{ verbosity|d(1) }}"

- name: Determining least loaded Centreon poller
  command: mysql {{ database|d("centreon_storage") }} -Ns -e "{{ query }}" #'select instance_id,name from instances where deleted = 0;'
  register: best_poller
  delegate_to: "{{ db_host|d('localhost')}}"
  changed_when: False

- name: Query output
  debug:
    msg: "Best poller: {{ best_poller.stdout.split('\t')[2] }} => {{ best_poller.stdout.split('\t')[0] }}ms. average host check latency"
    #verbosity: "{{ verbosity|d(1) }}"

- name: Add {{ ansible_hostname|upper }} ({{ ansible_fqdn }}) to Centreon
  centreon_host:
    url: "{{ centreon_url }}"
    username: "{{ centreon_api_user }}"
    password: "{{ centreon_api_pass }}"
    name: "{{ ansible_hostname|upper}}"
    alias: "{{ ansible_fqdn }}"
    ipaddr: "{{ ansible_fqdn }}"
    hosttemplates:
      - TH_ROOT_GLD_NS
    hostgroups:
      - HG_APP_DCK
    hostgroups_action: set
    instance: "{{ best_poller.stdout.split('\t')[2] }}"
    status: enabled
    state: present
    #params:
    #  - notes_url: "https://wiki.company.org/servers/{{ ansible_fqdn }}"
    #  - notes: "My Best server"
    applycfg: True
  delegate_to: localhost
  notify: "cent_api_applycfg"
